on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-electron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          npm ci
          npm run build
        working-directory: ./electron
      - uses: actions/upload-artifact@v2
        with:
          name: electron-bundle-js
          path: ./electron/app/compiled/bundle.js
  build-main:
    runs-on: ubuntu-latest
    steps:
      - run: cat /etc/hosts
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - run: |
          ./gradlew build
        working-directory: ./main
      - uses: actions/upload-artifact@v2
        with:
          name: main-build
          path: ./main/build/
  test-e2e:
    runs-on: ubuntu-latest
    needs:
      - build-electron
      - build-main
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/download-artifact@v2
        with:
          name: electron-bundle-js
          path: ./electron/app/compiled/bundle.js
      - uses: actions/download-artifact@v2
        with:
          name: main-build
          path: ./main/build/
      - run: npm ci
        working-directory: ./electron
      - run: npm test
        working-directory: ./electron
